### ISSUE TITLE
Conflicts w/ Unleveled

### ISSUE THREAD

**Issue by Prismcharge** [PoctorDepper/levelplus#1]
Trying to use both Levelplus and Unleveled at the same time causes the custom health bar provided by Levelplus to block any changes trying to be made to the player health by Unleveled. Unleveled is a mod which adds customization to the player and enemy health bar, adds group health bars, customizable damage numbers, etc (Its tied to another leveling mod). Features like Low health sounds and customizable damage numbers are unaffected (unable to test group health bars). 

Not sure how it would work, but a possible fix would be making the Custom health bar toggle-able or to add support for Unleveled mod. Also, I think adding an option to lock the Custom health bar would be helpful (one of the main reasons I tried using Unleveled).

Unleveled Mod does not have a direct mod page that I could find, so here is the Leveled RPG mod page: https://forums.terraria.org/index.php?threads/leveled-rpg-mod-port-to-tmod-project.58728/

**Comment by PoctorDepper** [comment]
I'll get on this for 0.2.0.0, thanks for the feedback!

**Comment by Prismcharge** [comment]
**Thank you!** Also, love the mod, keep up the good work! :   )

**Comment by PoctorDepper** [comment]
I did in fact fix this. With 1.4 adding actual health bar options, I will just be removing mine.
