### ISSUE TITLE
1.4 change the attribute gain to zero cause unkown error in character menu

### ISSUE THREAD

**Issue by greeedyadhd** [PoctorDepper/levelplus#10]
like melee damage from default to 0 and i did a bit of em
![error](https://user-images.githubusercontent.com/108164430/175755366-031e5e20-fdc1-4f1f-b093-fac55884f309.PNG)

**Comment by greeedyadhd** [comment]
it only started to happen after i reload it for the config changes was working before works after mod was disabled

**Comment by PoctorDepper** [comment]
Odd
