### ISSUE TITLE
No text when hovering over the nodes.

### ISSUE THREAD

**Issue by ghost** [PoctorDepper/LevelPlus#20]
I'm not sure when it started happening but I was using it with several other mods and it was working fine but now nothing appears when I hover over the nodes.

![image](https://user-images.githubusercontent.com/94040719/186037996-5f4eaa73-978a-464d-86a2-f3549aeaad70.png)
![image](https://user-images.githubusercontent.com/94040719/186038014-4d5d252a-68e8-419d-b31e-9aed567c2d10.png)

**Comment by MisterCirby** [comment]
Same here.

**Comment by MisterCirby** [comment]
Well i discovered something, the magic storage creates issues with it, so that´s the problem, i disabled that mod and now i can see the text without magic storage.

**Comment by PoctorDepper** [comment]
This issue is already posted on both the Discord and the Steam page
